version: '3'
services:
  webapp:
    build: webapp
    ports:
    - "5000:5000"
    volumes:
    - ./webapp/:/webapp
  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=ebcode
      - MYSQL_USER=ebcode
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
